# The URL the site will be built for
base_url = "https://ivypoledance.at/"
title = "IvyPoledance"
description = "Privatstunden, Workshops und Performances in Wien und Umgebung - Poledance & Polehooping"

theme = "adidoks"

compile_sass = true
build_search_index = true

taxonomies = [
  {name = "authors"},
]

[markdown]
highlight_code = false
external_links_target_blank = true
external_links_no_follow = true
external_links_no_referrer = true

[link_checker]
internal_level = "error"
external_level = "error"

[extra]
# Put all your custom variables here

[extra.footer]
info = " "

[[extra.menu.main]]
name = "Kurse"
section = "course"
url = "/courses/courses-and-booking/booking/"

[[extra.menu.main]]
name = "About"
section = "about"
url = "/about/"

[[extra.menu.main]]
name = "Testimonials"
section = "testimonials"
url = "/testimonials/"

[[extra.menu.main]]
name = "Polecamp"
section = "polecamp"
url = "/polecamp/"

[[extra.menu.social]]
name = "Instagram"
pre = '<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-instagram"><rect x="2" y="2" width="20" height="20" rx="5" ry="5"></rect><path d="M16 11.37A4 4 0 1 1 12.63 8 4 4 0 0 1 16 11.37z"></path><line x1="17.5" y1="6.5" x2="17.51" y2="6.5"></line></svg>'
url = "https://www.instagram.com/ivypole"

[[extra.menu.social]]
name = "Facebook"
pre = '<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-facebook"><path d="M18 2h-3a5 5 0 0 0-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 0 1 1-1h3z"></path></svg>'
url = "https://www.facebook.com/ivypoledance"

[[extra.menu.social]]
name = "Imprint"
pre = '<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-mail"><path d="M4 4h16c1.1 0 2 .9 2 2v12c0 1.1-.9 2-2 2H4c-1.1 0-2-.9-2-2V6c0-1.1.9-2 2-2z"></path><polyline points="22,6 12,13 2,6"></polyline></svg>'
url = "/imprint/"
